import type { User, BalanceHistoryEntry } from "./types";
import { subDays } from "date-fns";

export const users: User[] = [
  {
    id: "usr-001",
    name: "Alex Johnson",
    login: "alexj",
    avatar: "https://picsum.photos/seed/1/40/40",
    balance: 1250.75,
    deposits: 5000,
    withdrawals: 3749.25,
    winnings: 1500,
    game: "Blackjack",
    createdAt: subDays(new Date(), 5).toISOString(),
  },
  {
    id: "usr-002",
    name: "Maria Garcia",
    login: "mariag",
    avatar: "https://picsum.photos/seed/2/40/40",
    balance: 830.0,
    deposits: 2000,
    withdrawals: 1170,
    winnings: 400,
    game: "Roulette",
    createdAt: subDays(new Date(), 12).toISOString(),
  },
  {
    id: "usr-003",
    name: "James Smith",
    login: "jamess",
    avatar: "https://picsum.photos/seed/3/40/40",
    balance: 4500.0,
    deposits: 10000,
    withdrawals: 5500,
    winnings: 3200,
    game: "Poker",
    createdAt: subDays(new Date(), 25).toISOString(),
  },
  {
    id: "usr-004",
    name: "Patricia Brown",
    login: "pattyb",
    avatar: "https://picsum.photos/seed/4/40/40",
    balance: 200.5,
    deposits: 500,
    withdrawals: 299.5,
    winnings: 100,
    game: "Slots",
    createdAt: subDays(new Date(), 40).toISOString(),
  },
  {
    id: "usr-005",
    name: "Michael Miller",
    login: "mikem",
    avatar: "https://picsum.photos/seed/5/40/40",
    balance: 760.2,
    deposits: 1500,
    withdrawals: 739.8,
    winnings: 550,
    game: "Blackjack",
    createdAt: subDays(new Date(), 2).toISOString(),
  },
  {
    id: "usr-006",
    name: "Linda Davis",
    login: "lindad",
    avatar: "https://picsum.photos/seed/6/40/40",
    balance: 150.0,
    deposits: 300,
    withdrawals: 150,
    winnings: 50,
    game: "Slots",
    createdAt: subDays(new Date(), 8).toISOString(),
  },
  {
    id: "usr-007",
    name: "Robert Wilson",
    login: "robtw",
    avatar: "https://picsum.photos/seed/7/40/40",
    balance: 3205.9,
    deposits: 6000,
    withdrawals: 2794.1,
    winnings: 1800,
    game: "Poker",
    createdAt: subDays(new Date(), 18).toISOString(),
  },
  {
    id: "usr-008",
    name: "Jennifer Moore",
    login: "jennm",
    avatar: "https://picsum.photos/seed/8/40/40",
    balance: 990.0,
    deposits: 2500,
    withdrawals: 1510,
    winnings: 600,
    game: "Roulette",
    createdAt: subDays(new Date(), 32).toISOString(),
  },
  {
    id: "usr-009",
    name: "David Taylor",
    login: "davidt",
    avatar: "https://picsum.photos/seed/9/40/40",
    balance: 50.25,
    deposits: 100,
    withdrawals: 49.75,
    winnings: 10,
    game: "Slots",
    createdAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: "usr-010",
    name: "Susan Anderson",
    login: "susana",
    avatar: "https://picsum.photos/seed/10/40/40",
    balance: 2100.0,
    deposits: 4000,
    withdrawals: 1900,
    winnings: 1100,
    game: "Blackjack",
    createdAt: subDays(new Date(), 22).toISOString(),
  },
  {
    id: "usr-011",
    name: "William Thomas",
    login: "willt",
    avatar: "https://picsum.photos/seed/11/40/40",
    balance: 180.0,
    deposits: 500,
    withdrawals: 320,
    winnings: 80,
    game: "Poker",
    createdAt: subDays(new Date(), 14).toISOString(),
  },
  {
    id: "usr-012",
    name: "Jessica Jackson",
    login: "jessj",
    avatar: "https://picsum.photos/seed/12/40/40",
    balance: 1340.5,
    deposits: 3000,
    withdrawals: 1659.5,
    winnings: 700,
    game: "Roulette",
    createdAt: subDays(new Date(), 60).toISOString(),
  },
];


export const balanceHistoryData: BalanceHistoryEntry[] = [];
